"""Fingerprint Key Generator for Manual Override Matching.

This module generates stable fingerprint keys from device characteristics
that can be used to match and reuse manual labels across devices with
similar fingerprints (even if they have different MAC addresses).
"""

import hashlib
import json
import logging
from typing import Any

logger = logging.getLogger(__name__)


def generate_fingerprint_key(
    fingerprint_data: dict[str, Any] | None,
    mac: str | None = None,
    vendor_guess: str | None = None,
    model_guess: str | None = None,
) -> tuple[str, dict[str, Any]]:
    """Generate a stable fingerprint key from device characteristics.

    The key is generated by normalizing and hashing various fingerprint
    signals. This allows matching devices with similar characteristics
    even if they have different MAC addresses.

    Priority of signals (higher = more weight):
    1. DHCP Option 60 (Vendor Class Identifier) - very specific
    2. mDNS services - specific to device type
    3. SSDP server header - specific to device
    4. DHCP hostname patterns - less specific but useful
    5. OUI (first 3 bytes of MAC) - least specific fallback

    Args:
        fingerprint_data: Dict containing fingerprint signals
        mac: Device MAC address (used for OUI fallback)
        vendor_guess: Recognized vendor (for additional context)
        model_guess: Recognized model (for additional context)

    Returns:
        Tuple of (fingerprint_key, components_dict)
        - fingerprint_key: SHA256 hash (first 16 chars) of normalized signals
        - components_dict: Dict showing what signals were used
    """
    components: dict[str, Any] = {}
    signals: list[str] = []

    # Extract and normalize fingerprint signals
    if fingerprint_data:
        # DHCP Option 60 - Vendor Class Identifier (highest priority)
        vci = fingerprint_data.get("dhcp_opt60_vci") or fingerprint_data.get(
            "dhcp_vci"
        )
        if vci and isinstance(vci, str) and vci.strip():
            normalized_vci = vci.strip().lower()
            signals.append(f"vci:{normalized_vci}")
            components["dhcp_vci"] = vci.strip()

        # mDNS services
        mdns = fingerprint_data.get("mdns_services")
        if mdns:
            if isinstance(mdns, str):
                try:
                    mdns = json.loads(mdns)
                except json.JSONDecodeError:
                    mdns = [mdns]
            if isinstance(mdns, list) and mdns:
                # Sort for consistency
                sorted_mdns = sorted(str(s).lower() for s in mdns if s)
                if sorted_mdns:
                    signals.append(f"mdns:{','.join(sorted_mdns[:5])}")
                    components["mdns_services"] = sorted_mdns[:5]

        # SSDP server header
        ssdp = fingerprint_data.get("ssdp_server")
        if ssdp:
            if isinstance(ssdp, str):
                try:
                    ssdp = json.loads(ssdp)
                except json.JSONDecodeError:
                    ssdp = [ssdp]
            if isinstance(ssdp, list) and ssdp:
                # Take first SSDP server
                ssdp_val = str(ssdp[0]).strip().lower()
                if ssdp_val:
                    signals.append(f"ssdp:{ssdp_val}")
                    components["ssdp_server"] = ssdp[0]

        # DHCP hostname pattern (remove numeric suffixes for generalization)
        hostname = fingerprint_data.get("dhcp_opt12_hostname") or fingerprint_data.get(
            "dhcp_hostname"
        )
        if hostname and isinstance(hostname, str) and hostname.strip():
            # Normalize: lowercase, remove trailing numbers
            import re

            normalized_hostname = re.sub(r"[-_]?\d+$", "", hostname.strip().lower())
            if len(normalized_hostname) >= 3:
                signals.append(f"hostname:{normalized_hostname}")
                components["dhcp_hostname"] = hostname.strip()

        # User agent (extract key parts)
        ua = fingerprint_data.get("user_agent")
        if ua and isinstance(ua, str) and ua.strip():
            # Extract device identifier from UA if present
            ua_lower = ua.lower()
            if "iphone" in ua_lower or "ipad" in ua_lower:
                signals.append("ua:apple_mobile")
                components["user_agent_type"] = "apple_mobile"
            elif "android" in ua_lower:
                signals.append("ua:android")
                components["user_agent_type"] = "android"
            elif "windows" in ua_lower:
                signals.append("ua:windows")
                components["user_agent_type"] = "windows"
            elif "mac os" in ua_lower or "macintosh" in ua_lower:
                signals.append("ua:macos")
                components["user_agent_type"] = "macos"

    # Fallback: use OUI (first 3 bytes of MAC) if no other signals
    if not signals and mac:
        oui = mac.replace(":", "").replace("-", "")[:6].upper()
        if len(oui) == 6:
            signals.append(f"oui:{oui}")
            components["oui"] = oui

    # Add recognized vendor/model as additional context
    if vendor_guess:
        signals.append(f"vendor:{vendor_guess.lower()}")
        components["vendor_guess"] = vendor_guess
    if model_guess:
        signals.append(f"model:{model_guess.lower()}")
        components["model_guess"] = model_guess

    # Generate hash from sorted signals
    if signals:
        signals.sort()
        signal_string = "|".join(signals)
        fingerprint_key = hashlib.sha256(signal_string.encode()).hexdigest()[:16]
        logger.debug(
            f"Generated fingerprint key {fingerprint_key} from signals: {signals}"
        )
    else:
        # Fallback: use MAC address directly (unique per device)
        if mac:
            mac_normalized = mac.replace(":", "").replace("-", "").lower()
            fingerprint_key = hashlib.sha256(mac_normalized.encode()).hexdigest()[:16]
            components["mac_fallback"] = mac
        else:
            # Last resort: random-ish key
            fingerprint_key = hashlib.sha256(b"unknown").hexdigest()[:16]
            components["fallback"] = "unknown"

    return fingerprint_key, components


def match_fingerprint_key(
    fingerprint_data: dict[str, Any] | None,
    mac: str | None = None,
    vendor_guess: str | None = None,
    model_guess: str | None = None,
) -> str:
    """Generate a fingerprint key for matching purposes.

    This is a convenience wrapper around generate_fingerprint_key that
    returns only the key string.

    Args:
        fingerprint_data: Dict containing fingerprint signals
        mac: Device MAC address
        vendor_guess: Recognized vendor
        model_guess: Recognized model

    Returns:
        The fingerprint key string
    """
    key, _ = generate_fingerprint_key(
        fingerprint_data, mac, vendor_guess, model_guess
    )
    return key
